sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 156.226.179.157
    port: 3306
    database: sky_take_out
    username: root
    password: Huawei12#$%

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tP5EzzWCpC6y8iCwmhG
    access-key-secret: uJAuup5tv4NvvfVL0nnWdU1d1B66Bx
    bucket-name: sky-lxt-itcase

  redis:
    host: localhost
    port: 6379
    password:
    database: 10

  wechat:
    appid: wx8c770ce0cf990d1a
    secret: 1641dbd915692eef053284e94322e53f